import { createTheme } from "@vanilla-extract/css";
import { colorSchemeContract } from "./themeContracts.css";

export const lightScheme = createTheme(colorSchemeContract, {
  text: {
    light: "#616161",
    lightTransparent: "null",
    normal: "#1A1A1A",
    normalTransparent: "null",
    dark: "#000",
    darkTransparent: "null",
  },
  background: {
    light: "#FFFFFF",
    lightTransparent: "null",
    normal: "#F7F7F7",
    normalTransparent: "null",
    dark: "#E4E4E4",
    darkTransparent: "null",
  },
  primary: {
    light: "#38bdf8",
    lightTransparent: "#38bdf855",
    normal: "#3b82f6",
    normalTransparent: "#3b82f655",
    dark: "#0284c7",
    darkTransparent: "#0284c755",
  },
  secondary: {
    light: "#a78bfa",
    lightTransparent: "null",
    normal: "#8b5cf6",
    normalTransparent: "null",
    dark: "#7c3aed",
    darkTransparent: "null",
  },
  success: {
    light: "#34d399",
    lightTransparent: "null",
    normal: "#10b981",
    normalTransparent: "null",
    dark: "#059669",
    darkTransparent: "null",
  },
  error: {
    light: "#f87171",
    lightTransparent: "null",
    normal: "#ef4444",
    normalTransparent: "null",
    dark: "#dc2626",
    darkTransparent: "null",
  },
  warning: {
    light: "#fb923c",
    lightTransparent: "null",
    normal: "#f59e0b",
    normalTransparent: "null",
    dark: "#ea580c",
    darkTransparent: "null",
  },
});

export const darkScheme = createTheme(colorSchemeContract, {
  text: {
    light: "#CFCFCF",
    lightTransparent: "null",
    normal: "#F6F6F6",
    normalTransparent: "null",
    dark: "#FFFFFF",
    darkTransparent: "null",
  },
  background: {
    light: "#404040",
    lightTransparent: "#40404033",
    normal: "#262626",
    normalTransparent: "#26262633",
    dark: "#171717",
    darkTransparent: "#17171733",
  },
  primary: {
    light: "#7dd3fc",
    lightTransparent: "#7dd3fc33",
    normal: "#60a5fa",
    normalTransparent: "#60a5fa33",
    dark: "#0ea5e9",
    darkTransparent: "#0ea5e933",
  },
  secondary: {
    light: "#c4b5fd",
    lightTransparent: "#c4b5fd33",
    normal: "#c084fc",
    normalTransparent: "#c084fc33",
    dark: "#8b5cf6",
    darkTransparent: "#8b5cf633",
  },
  success: {
    light: "#34d399",
    lightTransparent: "#34d39933",
    normal: "#10b981",
    normalTransparent: "#10b98133",
    dark: "#059669",
    darkTransparent: "#05966933",
  },
  error: {
    light: "#f87171",
    lightTransparent: "#f8717133",
    normal: "#ef4444",
    normalTransparent: "#ef4444",
    dark: "#dc2626",
    darkTransparent: "#dc262633",
  },
  warning: {
    light: "#fb923c",
    lightTransparent: "#fb923c33",
    normal: "#f59e0b",
    normalTransparent: "#f59e0b33",
    dark: "#ea580c",
    darkTransparent: "#ea580c33",
  },
});
