import { createTheme } from "@vanilla-extract/css";
import { colorSchemeContract } from "./themeContracts.css";

export const lightScheme = createTheme(colorSchemeContract, {
  text: {
    light: "#616161",
    lightTransparent: "null",
    normal: "#1A1A1A",
    normalTransparent: "null",
    dark: "#000",
    darkTransparent: "null",
  },
  background: {
    light: "#FFFFFF",
    lightTransparent: "null",
    normal: "#F7F7F7",
    normalTransparent: "null",
    dark: "#E4E4E4",
    darkTransparent: "null",
  },
  primary: {
    light: "#38bdf8",
    lightTransparent: "null",
    normal: "#3b82f6",
    normalTransparent: "null",
    dark: "#0284c7",
    darkTransparent: "null",
  },
  secondary: {
    light: "#a78bfa",
    lightTransparent: "null",
    normal: "#8b5cf6",
    normalTransparent: "null",
    dark: "#7c3aed",
    darkTransparent: "null",
  },
  success: {
    light: "#34d399",
    lightTransparent: "null",
    normal: "#10b981",
    normalTransparent: "null",
    dark: "#059669",
    darkTransparent: "null",
  },
  error: {
    light: "#f87171",
    lightTransparent: "null",
    normal: "#ef4444",
    normalTransparent: "null",
    dark: "#dc2626",
    darkTransparent: "null",
  },
  warning: {
    light: "#fb923c",
    lightTransparent: "null",
    normal: "#f59e0b",
    normalTransparent: "null",
    dark: "#ea580c",
    darkTransparent: "null",
  },
});

export const darkScheme = createTheme(colorSchemeContract, {
  text: {
    light: "#CFCFCF",
    lightTransparent: "null",
    normal: "#F6F6F6",
    normalTransparent: "null",
    dark: "#FFFFFF",
    darkTransparent: "null",
  },
  background: {
    light: "#404040",
    lightTransparent: "null",
    normal: "#262626",
    normalTransparent: "null",
    dark: "#171717",
    darkTransparent: "null",
  },
  primary: {
    light: "#38bdf8",
    lightTransparent: "null",
    normal: "#3b82f6",
    normalTransparent: "null",
    dark: "#0284c7",
    darkTransparent: "null",
  },
  secondary: {
    light: "#a78bfa",
    lightTransparent: "null",
    normal: "#8b5cf6",
    normalTransparent: "null",
    dark: "#7c3aed",
    darkTransparent: "null",
  },
  success: {
    light: "#34d399",
    lightTransparent: "null",
    normal: "#10b981",
    normalTransparent: "null",
    dark: "#059669",
    darkTransparent: "null",
  },
  error: {
    light: "#f87171",
    lightTransparent: "null",
    normal: "#ef4444",
    normalTransparent: "null",
    dark: "#dc2626",
    darkTransparent: "null",
  },
  warning: {
    light: "#fb923c",
    lightTransparent: "null",
    normal: "#f59e0b",
    normalTransparent: "null",
    dark: "#ea580c",
    darkTransparent: "null",
  },
});
